Fix: Adding pagination and correcting all user retrieval
atlp-rwanda/e-commerce-bitcrafters-bn pull request #107
Opened 2024-06-17 07:30 UTC by AngeloChristian1

#### What does this PR do?
It fixes issues that were occurring in data retrieval

#### Description of Task to be completed?

- Added pagination to all get All endpoints
- Removed password from being sent when users are being retrieved
- 

#### How should this be manually tested?
On swagger visited relevant pages for testing

#### Questions:

2024-06-17 11:54 UTC, mpanoathos requested changes
Great work! but there are some changes to make

2024-06-17 11:54 UTC, mpanoathos commented on src/controllers/adminController.ts
> +      limit
Nice

2024-06-17 11:54 UTC, mpanoathos commented on src/controllers/productController.ts
> +    // const offset = (page - 1) * limit
Please remove commented codes since they are not performing anything

2024-06-17 11:54 UTC, mpanoathos commented on src/routes/userRoute.ts
> +  // isAuthenticated, checkPermission(UserRole.ADMIN),
Remember to remove this comments, this action needs to be performed by admin

2024-06-17 11:54 UTC, mpanoathos commented on src/services/notificationServices.ts
> +}
Nice

2024-06-17 15:22 UTC, mpanoathos approved these changes

2024-06-18 08:11 UTC, munezerobagira approved these changes

2024-06-18 08:11 UTC, merged