#187364716 Integrate HoundCI with badge attached to readme
atlp-rwanda/e-commerce-bitcrafters-bn pull request #26
Opened 2024-04-19 09:48 UTC by Impano1

**What does this PR do?**
Integrate HoundCI with a badge attached to readme 

**Description of Task to be completed?**
- Validate the codebase with standard style guides

**How should this be manually tested?**
- Configurations are displayed on README.md file

**What are the relevant pivotal tracker/Trello stories?**
#187364716

2024-04-19 16:51 UTC, munezerobagira commented
can you check your title and remember to add label

2024-04-24 13:15 UTC, mpanoathos approved these changes

2024-04-24 13:21 UTC, AngeloChristian1 approved these changes

2024-04-25 12:11 UTC, munezerobagira approved these changes

2024-04-25 12:17 UTC, munezerobagira reviewed
Can you check reason why there is no houndci check on PR?

2024-04-25 12:59 UTC, munezerobagira requested changes

2024-04-25 12:59 UTC, munezerobagira commented on .hound.yaml
> +#       - eslint-plugin:@typescript-eslint/recommended
```suggestion
```

2024-04-25 13:00 UTC, munezerobagira commented on .hound.yaml
> +#       - eslint-plugin:@typescript-eslint/recommended
is this comments or it part of configuration

2024-04-25 13:03 UTC, munezerobagira approved these changes

2024-04-25 13:03 UTC, merged