[#187364719] GitHub actions with readme badge
atlp-rwanda/e-commerce-bitcrafters-bn pull request #27
Opened 2024-04-19 09:59 UTC by Bananayosostene

Integration GitHub actions with readme badge 

# Why is this important

This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product

# Setting up continuous integration

2024-04-19 16:51 UTC, munezerobagira commented
can you check your title

2024-04-19 19:08 UTC, AngeloChristian1 commented
Add a pivotal id on the name of the PR

2024-04-21 17:58 UTC, Yvan-David requested changes

2024-04-21 17:58 UTC, Yvan-David commented on .github/workflows/node.js.yml
> +  push:
it should be configured to develop branch or any branch so that it doesn't depend on your branch

2024-04-21 19:16 UTC, Yvan-David submitted a review, later dismissed

2024-04-21 19:23 UTC, EricNiyo73 submitted a review, later dismissed

2024-04-22 07:51 UTC, munezerobagira requested changes

2024-04-22 07:51 UTC, munezerobagira commented on src/math.js
what is role of this js file?
It seem to build version of ts
can you remove it?

2024-04-22 07:51 UTC, munezerobagira commented on src/migrations/20240407175814-create-user.js
**normally** deleting migration file is not recommended

2024-04-22 07:51 UTC, munezerobagira commented on test/math.test.js
> +    it("should return 10 when have 8 + 2", () => {
this also seem build version of ts file,
can you remove it too?

2024-04-22 08:52 UTC, munezerobagira requested changes
can  you include this .nycrc.json configuration to make sure that the coverage it collected in all files
{
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules/**", "coverage/**"],
  "all": true
}

2024-04-23 16:48 UTC, munezerobagira requested changes

2024-04-23 16:48 UTC, munezerobagira commented on src/dummy.ts
> +export default Calculator
we don't need this dummy you can delete it

2024-04-23 16:48 UTC, munezerobagira commented on src/math.ts
we can also remove this files

2024-04-23 16:48 UTC, munezerobagira commented on test/dummy.test.ts
> +    })
```suggestion
```

2024-04-23 16:48 UTC, munezerobagira commented on test/math.test.ts
> +  });
```suggestion

```

2024-04-23 16:49 UTC, munezerobagira commented on src/dummy.ts
> +export default Calculator
we can use simple test as
expect(true).to.be(true)
all pass

2024-04-24 08:32 UTC, Bananayosostene commented on test/math.test.ts
> +  });
file was deleted

2024-04-24 14:20 UTC, Yvan-David approved these changes

2024-04-24 15:00 UTC, munezerobagira requested changes

2024-04-24 15:00 UTC, munezerobagira commented on src/math.ts
remove this file also

2024-04-24 15:00 UTC, munezerobagira commented on test/math.test.ts
> +    expect(sum(8, 2)).to.equal(10);
```suggestion
    expect(8+2).to.equal(10);
```
Can be as simple as that

2024-04-24 15:00 UTC, munezerobagira commented on test/math.test.ts
> +    expect(sub(8, 2)).to.equal(6);
```suggestion
    expect(8-2).to.equal(6);
```

2024-04-24 15:00 UTC, munezerobagira commented on test/math.test.ts
> +});
```suggestion
});
```

2024-04-24 21:04 UTC, EricNiyo73 approved these changes

2024-04-25 07:03 UTC, munezerobagira approved these changes

2024-04-25 07:04 UTC, merged