[#187364715] Setup ESLint and Pre-commit to run tests and ESLint format
atlp-rwanda/e-commerce-bitcrafters-bn pull request #35
Opened 2024-04-21 22:29 UTC by UwizeyimamaFurahaJustine

**PR Description**

This pull request introduces updates to the ESLint configuration and adds a pre-commit hook to ensure code quality and consistency across the project.

**Changes Made:**

**ESLint Configuration Configurations:**

- Updated ESLint configuration to comply to project standards and best practices.
- Added rules to enforce coding conventions, such as camelCase naming, consistent use of let and const, and spacing around directives.
- Configured ESLint to ignore the dist directory to prevent linting of compiled files.

**Pre-commit Hook Configuration:**

- Implemented a pre-commit hook using Husky to run ESLint and Prettier before every commit.
- Added a Bash script to execute Prettier formatting and ESLint linting on staged files.
- Configured the pre-commit hook to ensure that no code is committed with style violations or failing tests.

**Why This is Important:**

- ESLint ensures that code comply to coding standards, catches common errors, and maintains consistency across the codebase.
- The pre-commit hook automates the process of running ESLint, Prettier and Tests before commits, reducing the chance of introducing style violations or errors into the repository.
- By enforcing code quality checks before commits, we can maintain a high level of code quality and prevent the accumulation of technical debt.

**Testing:**

- Added tests to verify the functionality of the pre-commit hook and ESLint configuration.
- Wrote test cases to cover scenarios where code with style violations or failing tests is attempted to be committed.
- Tested the pre-commit hook by attempting to commit changes with intentional ESLint violations and ensuring that the commit was aborted.
- Ran ESLint and Prettier manually to verify that the configurations are correctly applied and enforced.

**Pivotal Tracker story**
#187364715

2024-04-22 04:48 UTC, AngeloChristian1 approved these changes, later dismissed

2024-04-22 04:52 UTC, EricNiyo73 submitted a review, later dismissed

2024-04-22 07:56 UTC, munezerobagira reviewed
can you also add the command to check perform the eslint check

2024-04-22 08:02 UTC, munezerobagira requested changes
you PR is missing .husky/
have initialized husky before committed the change
you can use this reference to learn on how you initialized it

2024-04-22 08:06 UTC, munezerobagira commented
and make sure ath that the eslint is run on all files except the migrations which are automatically generate by sequelize

2024-04-22 09:12 UTC, munezerobagira commented on .husky/pre-commit
> +
```suggestion
npx prettier --write . 

# Run ESLint
npx eslint  

npm test 
```
avoid this redirection as it might fail on windows

2024-04-22 09:13 UTC, munezerobagira requested changes

2024-04-22 09:13 UTC, munezerobagira commented on .prettierrc
> +  }
```suggestion
{
   
  }
``` can you add the valid prettier configuration

2024-04-23 16:51 UTC, munezerobagira requested changes

2024-04-23 16:51 UTC, munezerobagira commented on .husky/pre-commit
> +npx eslint
```suggestion
npx eslint  .
```

2024-04-23 17:06 UTC, munezerobagira commented on .husky/pre-commit
> +npx eslint
it would be better but if make it a npm script and 
run as npm run lint

2024-04-23 17:08 UTC, munezerobagira requested changes

2024-04-23 17:08 UTC, munezerobagira commented on .husky/pre-commit
> +npx eslint
if possible we can also  include the build script to make that build works

2024-04-24 12:55 UTC, munezerobagira approved these changes

2024-04-24 13:43 UTC, AngeloChristian1 approved these changes

2024-04-24 14:20 UTC, EricNiyo73 approved these changes

2024-04-24 14:48 UTC, merged