[#187364723] - Setup docker for backend application
atlp-rwanda/e-commerce-bitcrafters-bn pull request #36
Opened 2024-04-22 09:36 UTC by AngeloChristian1

**What does this PR do** 
Setting Up docker configurations 

**Task Included**
1. Initializing a Dockerfile
2. Setting up a docker-compose.yaml file that runs two services
    - Express Server
    - Postgress Database
  
**How should this be manually tested?**
- Before cloning the repo make sure that you have installed docker in your local machine
- Make sure that you fill in all necessary environment variables required
- Clone the repo and install the required packages
- cd into the repo in the terminal and run 
       - 'docker-compose up --build' : which will build the images and container
       - 'docker run -p e-commerce-bitcrafters-bn' : which will run the image
- Other necessary commands
    - 'docker login' : which will allow you to log into your docker account (Better if you have a desktop docker app)
    - 'docker compose up': It wakes up the container
    - 'docker compose down': It sleeps the container

**Any background context you want to provide?**
- Install docker
- Add docker extension on your editor for easy configurations

**Pivotal Tracker stories**
#187364723

2024-04-22 22:03 UTC, mpanoathos approved these changes

2024-04-24 14:22 UTC, Yvan-David approved these changes

2024-04-25 12:42 UTC, munezerobagira requested changes

2024-04-25 12:42 UTC, munezerobagira commented on .structure.env
its common to call this .env.example

2024-04-25 12:42 UTC, munezerobagira commented on .circleci/config.yaml
why do we have new file? seem to duplicate of config.yml

2024-04-25 12:42 UTC, munezerobagira commented on package.json
> +    "babel-build": "rm -rf build/ && babel src --out-dir build/src --extensions '.ts' --copy-files --source-maps && babel index.ts --out-file build/index.js --extensions '.ts' --copy-files",
why do we have 2 build, babel-build and build?

2024-04-25 12:42 UTC, munezerobagira commented on src/config/database.ts
> +export default  sequelize ;
why do we have this new file?

2024-04-25 12:47 UTC, munezerobagira commented on .dockerignore
> +./node_modules
do we need to have all these?

2024-04-25 12:47 UTC, munezerobagira commented on .gitignore
> +./dist
can you check if this is not duplicate?

2024-04-25 14:16 UTC, munezerobagira approved these changes

2024-04-25 14:18 UTC, merged