[#187364733] -Ft two factor authentication for sellers
atlp-rwanda/e-commerce-bitcrafters-bn pull request #46
Opened 2024-04-30 08:10 UTC by EricNiyo73

**What does this PR do?**
This PR introduces the functionality for users, specifically Sellers, to enable two-factor authentication (2FA) for added security when logging into the application.

 **Description of Task to be completed?**
The task involves implementing the logic to allow users to enable 2FA for their accounts. When 2FA is enabled for a user, they should be prompted to provide an additional authentication factor, such as an SMS code or authentication token, during the login process.

 **How should this be manually tested?**
Attempt to log in to the user account with 2FA enabled.
Verify that the login process prompts for a 2FA token.
Enter a valid 2FA token and submit the form.

 **Any background context you want to provide?**
Verify that the user is successfully logged in after the 2FA token is validated.
Implementing 2FA adds an extra layer of security to user accounts, especially for users with elevated privileges like Sellers who may have access to sensitive data or functionalities.

 **What are the relevant pivotal tracker/Trello stories?**
[#187364733]
 **Screenshots (if appropriate)**

2024-05-08 11:59 UTC, AngeloChristian1 commented on test/jwtConfiguration.test.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Try to remove these eslint comments

2024-05-08 11:59 UTC, AngeloChristian1 commented on package.json
> +    "test": "nyc mocha --require ts-node/register test/*.ts --timeout 800000 --exit",
why did you change the test command?
you can just add the timeout on the individual test you want to time

2024-05-08 12:06 UTC, UwizeyimamaFurahaJustine requested changes

2024-05-08 12:06 UTC, UwizeyimamaFurahaJustine commented on src/assets/emailTemplates/index.ts
I think you can rename this file to something else for better understanding.

2024-05-08 12:06 UTC, UwizeyimamaFurahaJustine commented on src/docs/signupDocs.ts
Also for better structure of project you can create new file for this doc.

2024-05-13 16:38 UTC, UwizeyimamaFurahaJustine approved these changes

2024-05-13 16:39 UTC, UwizeyimamaFurahaJustine approved these changes

2024-05-13 16:46 UTC, AngeloChristian1 approved these changes

2024-05-13 16:46 UTC, AngeloChristian1 commented on .codeclimate.yml
can you create a fix PR for this file

2024-05-13 16:46 UTC, AngeloChristian1 commented on src/utils/hashPassword.ts
there is another similar file in the utils named password.ts, This is not needed

2024-05-13 16:46 UTC, AngeloChristian1 commented on src/utils/hashPassword.ts
Hey, so there is a similar file in the rebased content named passwords.ts and it is the one we are using

2024-05-14 05:22 UTC, AngeloChristian1 approved these changes

2024-05-14 06:11 UTC, munezerobagira approved these changes

2024-05-14 06:14 UTC, merged