[#187364738] A seller should be able to add/create a product
atlp-rwanda/e-commerce-bitcrafters-bn pull request #47
Opened 2024-04-30 09:58 UTC by UwizeyimamaFurahaJustine

**PR Description**

2024-05-14 09:07 UTC, EricNiyo73 reviewed
Please add a video or screenshot demonstrating how this feature works.

2024-05-15 09:04 UTC, AngeloChristian1 reviewed
You did a good job, but we can work on the following
- Creating a stock table for storing the Stock keeping unit (stu) for every product
- Rebasing properly so that you only have you files, you can achieve this by reseting to the most recent commit made on develop and the discarding files you didn't modify.

So can work on those changes.
Regards

2024-05-15 09:04 UTC, AngeloChristian1 commented on src/controllers/LoginController.ts
> +
What are these for?

2024-05-15 09:04 UTC, AngeloChristian1 commented on src/controllers/productController.ts
> +      if (!name || !price || !categoryId || !expiryDate || !bonus || !sku) {
I think it is more convenient for a product to have a category name no categoryId, but even this is ok

2024-05-17 06:32 UTC, EricNiyo73 requested changes
It seems like you are repeating some codes, just try to handle that duplicates.

2024-05-17 06:32 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +      }
It seems kike like you are repeating some snippets of codes, I think this error handling must be done by validateRrequest middleware , which means you  have to pass it into Product route.

```
router.post(
  '/collection',
  isAuthenticated, validateRequest(CollectionSchema, 'body'),
  checkPermission(UserRole.SELLER),
  productController.createCollection,
)
```

2024-05-17 06:32 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +      }
you are repeating some snippets of codes, I think must be done by joi schema  validation, You have passed out into your route.

2024-05-17 07:29 UTC, EricNiyo73 requested changes

2024-05-17 07:29 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +      const collection = await Collection.create({ name })
Also here you can save the user (userId) who created that collection, this can be helpful.

2024-05-17 09:11 UTC, AngeloChristian1 approved these changes

2024-05-17 09:32 UTC, EricNiyo73 approved these changes

2024-05-17 15:01 UTC, munezerobagira commented on src/routes/productRoute.ts
> +)
```suggestion
router.post(
  '/collections/:collectionId/items',
  isAuthenticated,
  checkPermission(UserRole.SELLER),
  configureMulter,
  validateRequest(productSchema, 'body'),
  productController.addProduct,
)
```
it would better if the route is descriptive

2024-05-17 15:01 UTC, munezerobagira commented on src/database/models/collectionModel.ts
> +        },
We can also add description  for the collection

2024-05-17 15:01 UTC, munezerobagira commented on src/controllers/productController.ts
> +        collectionId,
You need to check if the seller is adding product to collection that exists

2024-05-19 18:23 UTC, munezerobagira approved these changes

2024-05-19 18:26 UTC, merged