[#187364741] A User should be able to view a specific item
atlp-rwanda/e-commerce-bitcrafters-bn pull request #50
Opened 2024-05-01 09:57 UTC by Bananayosostene

**What does this PR do?**
This PR enhances the application's functionality to allow users, both Sellers and Buyers, to view specific items. It ensures that the retrieval process is robust and secure, providing the appropriate response based on the user's role and the item's availability.

**Description of Task to be completed?**
The task involves implementing endpoints to retrieve the details of a specific item. Different scenarios are considered, including cases where the item is in a seller's collection, does not exist in the seller's collection, or when the requesting user is a buyer. Validation checks are implemented to ensure the integrity and security of the retrieval process.

**How should this be manually tested?**
Send a GET request to retrieve the details of a specific item.
Test various scenarios:
Verify the response when the target item exists in the seller's collection.
Check the response when the item does not exist in the seller's collection.
Test the response for buyer users, ensuring they can view available items.
Validate the response for scenarios where the request body fails validation checks or the token is not of the seller role.
Ensure appropriate error responses are returned when necessary.
Confirm that the response objects contain the correct status codes, messages, and item details.
Any background context you want to provide?
Implementing this feature improves the user experience by providing seamless access to item details based on user roles and item availability. It ensures that users, whether Sellers or Buyers, can efficiently retrieve the information they need.

**What are the relevant pivotal tracker/Trello stories?**
[#187364733]

**Screenshots (if appropriate)**
[N/A]

**Questions:**
[If there are any questions or concerns, please feel free to raise them here.]

2024-05-12 15:50 UTC, AngeloChristian1 reviewed
Nice work, you can try to update the model by adding more columns for product

2024-05-12 15:50 UTC, AngeloChristian1 commented on src/database/models/ItemModel.ts
> +    },
You can add other attributes like price, category, Images, expireDate,... and others

2024-05-22 14:31 UTC, Bananayosostene commented
Please give me comment to this PR fill free also I did self review, Thank you!!!

2024-05-22 14:33 UTC, Yvan-David requested changes
I think instead of creating a getProduct controller as a file you should use product Controller file and creat there your functions 

also remember to use Product services file to access some functions instead of recreating them


Please remember to put some screenshots or video to see your swagger documentation

2024-05-22 18:23 UTC, EricNiyo73 requested changes

2024-05-22 18:23 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +          })
The product which is unavailable ,bought  or expired are not allowed to be displayed to the buyer
And also I think the admin can view all the products posted for checking if the user has not posted the illegal products.

2024-05-22 18:23 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +      if (userRole === 'seller') {
Import **enum userRole from userModel** and use it instead

2024-05-23 19:46 UTC, Yvan-David approved these changes
Great Job
As shown in the video provided

2024-05-24 06:03 UTC, EricNiyo73 approved these changes

2024-05-24 06:43 UTC, munezerobagira approved these changes

2024-05-24 06:44 UTC, merged