#[187364740] A seller should be able to delete a specific item from their collection
atlp-rwanda/e-commerce-bitcrafters-bn pull request #51
Opened 2024-05-02 04:51 UTC by Yvan-David

#### What does this PR do?

 - endpoint handles scenario 1 where a user token is of role seller but the item does not exist
 - endpoint handles scenario 2 where a user token is of role seller and the item already exist and the body is validated
 - endpoint handles scenario 3 when request body fails any validation checks
 - validate all inputs for sanity

#### Description of Task to be completed?
     As a Seller
    I should be able to delete a specific item in my colletion
    Such that I can remove items I no longer deal in/were erroneously added

#### How should this be manually tested?

  -  Using swagger documentation
  -  Using postman
  - Link to Loom recording: ()

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

   -  #187364740

#### Screenshots (if appropriate)

#### Questions:

2024-05-06 20:26 UTC, Bananayosostene commented
There are same checks which are not successful it caused by coverage, so increase coverage

2024-05-06 23:12 UTC, Yvan-David commented
> There are same checks which are not successful it caused by coverage, so increase coverage

they are unsuccessful because coverage have decreased and it can not always be 100

2024-05-07 08:01 UTC, Bananayosostene approved these changes

2024-05-19 17:43 UTC, EricNiyo73 requested changes

2024-05-19 17:43 UTC, EricNiyo73 commented on src/database/models/productModel.ts
> +
Why this model does not have a collectionID, The seller can create or delete a specific item from their collection, which means foreign key from Collection Model is needed.

2024-05-19 17:51 UTC, EricNiyo73 requested changes

2024-05-19 17:51 UTC, EricNiyo73 commented on src/controllers/productController.ts
> +          }
How the deleted Product can be displayed??
May be you can return only message instead

2024-05-20 07:48 UTC, AngeloChristian1 reviewed
Great work, please see if you can work on the suggestions
Regards

2024-05-20 07:48 UTC, AngeloChristian1 commented on src/controllers/productController.ts
> +    static async deleteProduct(req: Request, res: Response) {
I think you nedd to first check if the product is in their collection

2024-05-20 07:48 UTC, AngeloChristian1 commented on src/controllers/productController.ts
> +      }
Won't this be a better implementation?
```suggestion
      if(!product){
      return res.status(410).json({message: "item not found"});
      }
      await deleteProductById(sellerId, productId)
       return res.status(200).json({message: "item deleted"})
```

2024-05-20 08:00 UTC, Yvan-David commented on src/controllers/productController.ts
> +      }
thanks for the suggestion

2024-05-20 08:18 UTC, AngeloChristian1 approved these changes

2024-05-20 09:56 UTC, EricNiyo73 approved these changes

2024-05-20 21:04 UTC, munezerobagira requested changes

2024-05-20 21:04 UTC, munezerobagira commented on src/controllers/productController.ts
> +import { deleteProductById, getProductById } from '../services/productServices'
```suggestion
import { deleteProductById, getProductById } from '../services/productServices'
```
is productServices or productService

2024-05-20 21:04 UTC, munezerobagira commented on src/docs/productDocs.ts
> + * /collections/{productId}:
```suggestion
 * /collections/products/{productId}:
```

2024-05-20 21:04 UTC, munezerobagira commented on src/controllers/productController.ts
> +        return res.status(410).json({message: "item not found"});
```suggestion
        return res.status(404).json({message: "item not found"});
```
 check  if this is correct  status code

2024-05-23 10:06 UTC, munezerobagira approved these changes

2024-05-23 10:41 UTC, merged