[#187364736] Admin can disable account for various reasons
atlp-rwanda/e-commerce-bitcrafters-bn pull request #52
Opened 2024-05-02 07:09 UTC by mpanoathos

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2024-05-18 15:02 UTC, Impano1 approved these changes

2024-05-19 17:30 UTC, Yvan-David requested changes
Please try to provide the req.body that provides reasons for account suspension

Also an email should be send to the user after the account is disabled

2024-05-19 17:30 UTC, Yvan-David commented on src/middlewares/authenticationMiddleware.ts
> +    console.log(error)
I think you shouldn't have touched to this file as there is no new changes to be added
and console.log() is not supported by eslint try to replace it

2024-05-23 01:44 UTC, Yvan-David requested changes
you did a great job but they are some files you changed that didn't need to be changed like loginController and authenticationMiddleware please revert the changes to reduce risks of conflicts

2024-05-23 09:52 UTC, Yvan-David approved these changes
Great job on working on the reviews and also the whole feature

2024-05-23 17:10 UTC, UwizeyimamaFurahaJustine reviewed
You can work on that request, otherwise you have done a good work.

2024-05-23 17:10 UTC, UwizeyimamaFurahaJustine commented on test/changeStatus.test.ts
> +  });
If you are not using this test its better to remove it instead of commenting it.

2024-05-23 17:13 UTC, UwizeyimamaFurahaJustine commented on test/changeStatus.test.ts
> +  });
If you are not using this test its better to remove it instead of commenting it

2024-05-23 17:37 UTC, UwizeyimamaFurahaJustine approved these changes

2024-05-26 17:41 UTC, munezerobagira approved these changes

2024-05-26 17:43 UTC, merged