Fix: Removing ESLint errors
atlp-rwanda/e-commerce-bitcrafters-bn pull request #57
Opened 2024-05-09 18:31 UTC by UwizeyimamaFurahaJustine

**What does this PR do?**

Removing ESLint errors 

**Description of Task to be completed?**

Adding configurations to handle ESLint errors.

**What are the relevant pivotal tracker/Trello stories?**

**Screenshots (if appropriate)**

2024-05-09 19:00 UTC, munezerobagira requested changes

2024-05-09 19:00 UTC, munezerobagira commented on .eslintrc.json
> +    "no-console":"off",
```suggestion
```
This rule ensure that no console log are shipped into production. Mostly console is used for debbugging purpose, if want to log some information you can use loggers like winston
https://github.com/winstonjs/winston

2024-05-09 19:00 UTC, munezerobagira commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "off",
This rule ensures that typescript is used correctly, so its not ideal to remove it
```suggestion
```

2024-05-09 19:00 UTC, munezerobagira commented on .eslintrc.json
> +    "strict":"off",
```suggestion
```
this is very important too

2024-05-09 21:04 UTC, munezerobagira approved these changes

2024-05-09 21:13 UTC, mpanoathos approved these changes

2024-05-09 21:13 UTC, mpanoathos commented on .eslintrc.json
> +    "@typescript-eslint/no-namespace": "off"
Nice

2024-05-10 04:37 UTC, AngeloChristian1 approved these changes

2024-05-10 05:41 UTC, EricNiyo73 approved these changes

2024-05-10 06:26 UTC, Bananayosostene approved these changes

2024-05-10 06:39 UTC, merged