Feature (View Cart): A buyer should be able to clear their cart
atlp-rwanda/e-commerce-bitcrafters-bn pull request #74
Opened 2024-05-23 08:24 UTC by AngeloChristian1

**What does this PR do?**

 Clearing of the buyer's cart, including emptying the cart in the buyer's session and resetting the cart total to zero.

**Description of Task to be completed?**

1. Empty the buyer's cart.
2. Reset the cart total to zero.
3. Return a cart cleared confirmation message to the frontend.

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

[Delivers #187364748]

2024-05-28 12:03 UTC, Yvan-David requested changes
you've changed the whole files you worked please revert the changes and remain only  with changes on your feature to reduce conflicts

2024-05-29 08:07 UTC, UwizeyimamaFurahaJustine approved these changes
Good job

2024-05-29 16:58 UTC, Yvan-David approved these changes
Great Job

2024-05-30 05:20 UTC, munezerobagira approved these changes

2024-05-30 05:20 UTC, merged