#[187364745] A buyer should be able to provide a review on a product
atlp-rwanda/e-commerce-bitcrafters-bn pull request #75
Opened 2024-05-23 11:50 UTC by Yvan-David

#### What does this PR do?

-      endpoint handles get all reviews with ratings and feedback
-      endpoint handles create review with ratings and feedback

#### Description of Task to be completed?
    ###  As a Buyer

1.     I should be able to give a review on a bought product
2.     any user should be able to see all 
3.     review include rating and feedback

#### How should this be manually tested?

  -  Using swagger documentation
  -  Using postman
  - Link to Loom recording: [https://www.loom.com/share/aad4b83c738f4e37b3e8282662b3d322?sid=75e1b8d7-f4ee-4c1b-85be-51040fd77324](https://www.loom.com/share/aad4b83c738f4e37b3e8282662b3d322?sid=75e1b8d7-f4ee-4c1b-85be-51040fd77324)
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

   -  #187364745

#### Screenshots (if appropriate)

#### Questions:

2024-05-23 18:02 UTC, mpanoathos requested changes

2024-05-23 18:02 UTC, mpanoathos commented on src/controllers/reviewsController.ts
> +    });
can you consider using Review.create instead since it directly saves changes to the db

2024-05-23 18:02 UTC, mpanoathos commented on src/controllers/reviewsController.ts
> +    });
Nicely done

2024-05-23 22:07 UTC, mpanoathos approved these changes

2024-06-03 18:07 UTC, Bananayosostene approved these changes

2024-06-03 18:07 UTC, Bananayosostene commented on src/controllers/reviewsController.ts
> +export const getAllReviews = async (req: Request, res: Response) => {
we can get review that is good so think about how we can get all product details includes its reviews information

2024-06-04 06:59 UTC, munezerobagira approved these changes
Good work

2024-06-04 07:00 UTC, merged