[#187364750] A user should be able to search a product
atlp-rwanda/e-commerce-bitcrafters-bn pull request #77
Opened 2024-05-25 09:01 UTC by Bananayosostene

**What does this PR do?**
This PR implements the feature allowing users to search for products. Users can now search by product name, price range, category, and a combination of these criteria using an AND operation.

**Description of Task to be completed?**
The task involves creating a search functionality for products on the e-commerce platform. Users, particularly buyers, need the ability to search for products based on various criteria such as name, price range, and category. The search can also combine multiple criteria to refine the results further. This feature enhances the user experience by making it easier for buyers to find products that meet their specific needs.

**How should this be manually tested?**
To manually test this feature, navigate to the search bar on the product listing page. Enter a product name, select a price range, and/or choose a category to search within. Verify that the results displayed match the search criteria provided. Additionally, test combinations of these criteria to ensure the AND operation is functioning correctly. For example, search for products within a certain price range and category to see if the results accurately reflect both conditions.

**Any background context I want to provide?**
Before this feature, users could not refine their searches effectively, leading to a potentially frustrating shopping experience. Implementing this search functionality addresses this issue by providing a more intuitive and efficient way to find products. This change aims to enhance overall user satisfaction and engagement on the platform.

**Relevant pivotal tracker/Trello stories**

**Video**

Questions:
If you have any questions or need further clarification about this feature, please feel free to ask.

2024-05-28 11:52 UTC, Yvan-David requested changes

2024-05-28 11:52 UTC, Yvan-David commented on src/controllers/productController.ts
they are many changes on this file while you only worked on one function please revert them to reduce conflicts

2024-05-28 12:07 UTC, Yvan-David requested changes

2024-05-28 12:07 UTC, Yvan-David commented on src/controllers/productController.ts
resolve conflicts

2024-05-31 09:43 UTC, UwizeyimamaFurahaJustine approved these changes
Good job

2024-05-31 09:48 UTC, Yvan-David approved these changes

2024-05-31 09:48 UTC, Yvan-David commented on .github/workflows/ci.yml
> -
remove this file
as a change by adding that space you deleted

2024-05-31 10:06 UTC, munezerobagira requested changes
can you remove this logs

2024-05-31 10:50 UTC, munezerobagira approved these changes

2024-05-31 10:51 UTC, merged