Feat Expired Products should not appear on the list of the available products 187364755
atlp-rwanda/e-commerce-bitcrafters-bn pull request #80
Opened 2024-05-28 08:05 UTC by Yvan-David

#### What does this PR do?

#### Description of Task to be completed?

1.  Expiry Date Check: Implement a mechanism to check if a product's expiration date has passed.
2. Product Status Update: Automatically update the product's status to "expired" when its expiration date is in the past.
3. Product Removal: Ensure that expired products are removed from the list of available products.
4. Email Notification: Send an email to the merchant when a product is marked as expired.

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2024-05-29 18:01 UTC, mpanoathos requested changes

2024-05-29 18:01 UTC, mpanoathos commented on src/utils/productExpiryCronJob.ts
> +  });
I think would be better if it goes in controllers since it will not be re-used again

2024-05-30 06:34 UTC, mpanoathos approved these changes

2024-05-30 06:45 UTC, Bananayosostene approved these changes

2024-05-30 09:10 UTC, munezerobagira approved these changes

2024-05-30 09:10 UTC, merged