Buyer should be able to update their cart [#187364747]
atlp-rwanda/e-commerce-bitcrafters-bn pull request #82
Opened 2024-05-28 09:02 UTC by Bananayosostene

**What does this PR do?**
This PR implements the feature allowing buyers to update their cart. Buyers can now update the quantities of items in their cart, and the system will store these updates in the buyer's session, retrieve product details from the database, and calculate the new cart total.

**Description of Task to be completed?**
The task involves creating functionality for updating the buyer's cart in the e-commerce platform. The backend will handle updates to the cart, including storing the updated cart in the buyer's session, validating that all quantities are positive integers, retrieving product details (name, price, image) from the database for each item in the updated cart, calculating the new cart total by summing the prices of the items in the updated cart, and returning an updated cart confirmation message to the frontend to be displayed to the buyer.

**How should this be manually tested?**
To manually test this feature, make a POST request to update the cart via the cart ID. Verify that the updated cart is stored in the buyer's session. Check that the product details for each item in the updated cart are correctly retrieved from the database. Ensure that the new cart total is accurately calculated by summing the prices of the items in the updated cart. Confirm that an updated cart confirmation message is sent to the frontend and displayed to the buyer.

**Any background context you want to provide?**
Before this feature, buyers were unable to update their carts dynamically, which could lead to a less flexible and less user-friendly shopping experience. Implementing this feature allows buyers to easily manage and update their carts, enhancing their overall shopping experience on the platform.

**Relevant pivotal tracker/Trello stories?**

**video**

**Questions:**
If you have any questions or need further clarification about this feature, please feel free to ask.

2024-05-31 06:08 UTC, Yvan-David requested changes
Good Job
it will be better if you:
  - make sure the quantity user added of product does not exceed the quantity in stock
  - on success a confirmation message should be seen and also the carts' items and their total not only the item you updated

2024-05-31 11:01 UTC, Bananayosostene commented
Thank you David, to check the quantity is necessary but i think the conformation message will use pop on front end not necessary to the email and notification will be sent for order and even payment

2024-06-02 19:27 UTC, Yvan-David approved these changes
Good job

2024-06-02 19:55 UTC, AngeloChristian1 approved these changes

2024-06-03 09:41 UTC, munezerobagira approved these changes

2024-06-03 09:42 UTC, merged