[#187364753] Buyer should be able to checkout
atlp-rwanda/e-commerce-bitcrafters-bn pull request #84
Opened 2024-05-28 11:26 UTC by EricNiyo73

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2024-05-29 03:52 UTC, munezerobagira requested changes

2024-05-29 03:52 UTC, munezerobagira commented on src/validations/orderValidation.ts
> +    .regex(/^(078|079|072|073)\d{7}$/)
You use joi object to validate the phone number instead of using your own

2024-05-30 07:44 UTC, Bananayosostene approved these changes

2024-05-30 07:51 UTC, Bananayosostene commented on test/middlewares.spec.ts
> +    // expect(res.status.calledWith(404)).to.be.true
remove those comments if they are useless

2024-05-30 08:18 UTC, Bananayosostene approved these changes

2024-05-30 12:05 UTC, UwizeyimamaFurahaJustine approved these changes
Good Job

2024-05-30 18:31 UTC, AngeloChristian1 approved these changes

2024-05-30 20:01 UTC, munezerobagira requested changes

2024-05-30 20:01 UTC, munezerobagira commented on src/controllers/checkoutController.ts
> +      )
```suggestion
      const totalAmount = cart.items.reduce(
        (total, item) =>total+ item.price * item.quantity,
        0,
      )
```

2024-05-30 20:21 UTC, munezerobagira approved these changes

2024-05-30 20:25 UTC, merged