[#187364756] User should be prompted to update password in x amount of time
atlp-rwanda/e-commerce-bitcrafters-bn pull request #92
Opened 2024-05-31 14:09 UTC by mpanoathos

#### What does this PR do?
User is able to update password, And user will be requested to update his password after a certain time
#### Description of Task to be completed?
- Update password
- Prompt to update password

#### How should this be manually tested?
- Using swagger 

#### What are the relevant pivotal tracker/Trello stories?
Delivers[#187364756]
#### Screenshots (if appropriate)

#### Questions:

2024-06-06 13:32 UTC, Yvan-David requested changes
please squash your commits to remain with only one commit message and
also provide a screenshot or a video to show how your feature works

2024-06-06 16:48 UTC, munezerobagira requested changes

2024-06-06 16:48 UTC, munezerobagira commented on src/controllers/LoginController.ts
> +    res
```suggestion
```
We can use reset password controller instead

2024-06-07 04:48 UTC, munezerobagira approved these changes

2024-06-07 08:35 UTC, Yvan-David approved these changes
Great Job
I saw that the tests that are failing are not yours and there is a fix PR for them in the way

2024-06-08 10:50 UTC, EricNiyo73 approved these changes

2024-06-08 10:51 UTC, merged